In [44]:
import re
import json
from collections import defaultdict
import os

# Input and output files
input_js_file = "C:\\Users\\zakaria\\workspace\\banania-remake\\game_js\\level\\level.js"
output_json_file = "C:\\Users\\zakaria\\workspace\\banania-remake\\\\banania_pygame\\assets\\levels\\levels.json"
# Check if input file exists
if not os.path.exists("C:\\Users\\zakaria\\workspace\\banania-remake\\"):
    raise FileNotFoundError("The specified path does not exist: C:\\Users\\zakaria\\")
if not os.path.isfile(input_js_file):
    raise FileNotFoundError(f"Input file not found: {input_js_file}")

# Make sure output directory exists
os.makedirs(os.path.dirname(output_json_file), exist_ok=True)

# Read the JS file
with open(input_js_file, "r", encoding="utf-8") as f:
    js_content = f.read()

# Regex to match level arrays
pattern = re.compile(r"EXTERNAL_LEVELS\[(\d+)\]\[(\d+)\]\s*=\s*new Array\((.*?)\);")

# Use defaultdict to collect rows by level
levels_dict = defaultdict(list)

# Find all matches
for lvl_idx, row_idx, numbers in pattern.findall(js_content):
    lvl_idx = int(lvl_idx)
    row_idx = int(row_idx)
    row = [int(n.strip()) for n in numbers.split(",")]
    levels_dict[lvl_idx].append((row_idx, row))

# Sort rows and build the final levels list
json_levels = []
for lvl_idx in sorted(levels_dict.keys()):
    sorted_rows = [row for _, row in sorted(levels_dict[lvl_idx])]
    json_levels.append(sorted_rows)

# Save to JSON
with open(output_json_file, "w", encoding="utf-8") as f:
    json.dump({"levels": json_levels}, f, indent=2)

print(f"Converted {len(json_levels)} levels to {output_json_file}")

Converted 51 levels to C:\Users\zakaria\workspace\banania-remake\\banania_pygame\assets\levels\levels.json


In [48]:
import json
import numpy as np

path  = "C:\\Users\\zakaria\\workspace\\banania-remake\\banania_pygame\\assets\\levels\\levels.json"

with open(path, "r") as f:
    data = json.load(f)

levels = data["levels"]

# Convert levels to numpy arrays
level_arrays = [np.array(level) for level in levels]
print(level_arrays[0])

[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 3 3 3 3 0 0 0 3 3 3 3 0]
 [0 3 0 0 3 6 6 6 3 0 0 3 0]
 [0 3 0 0 0 0 0 0 0 0 0 3 0]
 [0 3 3 0 5 5 5 5 5 0 3 3 0]
 [0 0 6 0 5 0 0 0 5 0 6 0 0]
 [0 0 6 0 5 0 2 0 5 0 6 0 0]
 [0 0 6 0 5 0 0 0 5 0 6 0 0]
 [0 3 3 0 5 5 5 5 5 0 3 3 0]
 [0 3 0 0 5 0 0 0 5 0 0 3 0]
 [0 3 0 0 5 0 2 0 5 0 0 3 0]
 [0 3 0 0 5 0 0 0 5 0 0 3 0]
 [0 3 3 0 5 5 5 5 5 0 3 3 0]
 [0 0 6 0 5 0 0 0 5 0 6 0 0]
 [0 0 6 0 5 0 2 0 5 0 6 0 0]
 [0 0 6 0 5 0 0 0 5 0 6 0 0]
 [0 3 3 0 5 5 5 5 5 0 3 3 0]
 [0 3 0 0 0 0 0 0 0 0 0 3 0]
 [0 3 0 0 3 6 6 6 3 0 0 3 0]
 [0 3 3 3 3 0 0 0 3 3 3 3 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]
